version: '3.7'

services:
  configserver:
    image: akmalalikhujaev/config-server:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
  licensingservice:
    image: akmalalikhujaev/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SERVER_PORT=8080"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CLOUD_CONFIG_URI=http://configserver:8071"
    depends_on:
      configserver:
        condition: service_started
