version: '3.7'

services:
  configserver:
    image: akmalalikhujaev/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: SECRETKEY
    networks:
      backend:
        aliases:
          - "configserver"
  licensingservice:
    image: akmalalikhujaev/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: "8080"
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
      ENCRYPT_KEY: "SECRETKEY"
    depends_on:
      configserver:
        condition: service_started
    networks: backend

networks:
  backend:
    driver: bridge

